@ECHO running self test
VER
HELLO
HELLO.EXE
TYPE README.TXT
COPY README.TXT COPY.TXT
TYPE COPY.TXT
DEL COPY.TXT
DIR
TSRTEST
TSRTEST
OVLTEST
MEM
DOSINT
HDTEST
CFGTEST
C:
DIR
ENVTEST
A:
ENVTEST
FCBTEST ALPHA BETA
ECHO redirect and pipe
DIR > DIRLIST.TXT
TYPE DIRLIST.TXT
ECHO tail-line >> DIRLIST.TXT
TYPE README.TXT | PIPETEST
PIPETEST < README.TXT
DEL DIRLIST.TXT
LFNTEST
EMSTEST
REM MYDOS 自身でディスクを作る。B: は MYDOS 以外の道具で作った
REM ごく普通の FAT12 フロッピー。これを FORMAT で作り直し、SYS で
REM 起動できるようにする。テストの最後に、そのディスクから起動する。
FORMAT B: /V:NEWDISK < YES.TXT
SYS B:
DIR B:
XMSTEST
REM XMS のブロック転送でアンリアルモードに出入りしたあと、
REM ハードディスクを触れるかどうか。ここで転ぶと再起動していた。
C:
DIR
A:
ECHO after XMS block move
REM ハードディスクにも入れてみる。SETUP が FDISK / FORMAT / SYS を
REM 順に呼び、CONFIG.SYS と AUTOEXEC.BAT も書き下ろす。
REM テストの最後にこのディスクから起動する。
SETUP C: < YES.TXT
DOSTEST
